//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiaraMail.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChiaraMail.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t supplied the {0} for this e-mail address so it won&apos;t be enabled for ECS.{1}{1}Do you want to continue? .
        /// </summary>
        internal static string account_validation {
            get {
                return ResourceManager.GetString("account_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application |*.exe.
        /// </summary>
        internal static string Application__exe {
            get {
                return ResourceManager.GetString("Application__exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account registration confirmation has been e-mailed to you.{0}{0}To activate your ChiaraMail account, select the link in the message{0}and then enter your content server password into the password field..
        /// </summary>
        internal static string auto_register_info {
            get {
                return ResourceManager.GetString("auto_register_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string blank_label {
            get {
                return ResourceManager.GetString("blank_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc:.
        /// </summary>
        internal static string cc_label {
            get {
                return ResourceManager.GetString("cc_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ChiaraMail {
            get {
                object obj = ResourceManager.GetObject("ChiaraMail", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChiaraMail_1 {
            get {
                object obj = ResourceManager.GetObject("ChiaraMail_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChiaraMailIcon {
            get {
                object obj = ResourceManager.GetObject("ChiaraMailIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChiaraMailIcon_32 {
            get {
                object obj = ResourceManager.GetObject("ChiaraMailIcon_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify ECS server password, name and port for the given e-mail address.
        /// </summary>
        internal static string Config_Alert_Missing_Props {
            get {
                return ResourceManager.GetString("Config_Alert_Missing_Props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Default).
        /// </summary>
        internal static string config_default_tag {
            get {
                return ResourceManager.GetString("config_default_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECS messaging may be hosted by the public content server (managed by ChiaraMail and whose server name is www.chiaramail.com) or by a private server, e.g., by your bank. You may configure private servers here, by specifying the content server name, port, account password and other settings. The owner of the content server will provide those values when you register..
        /// </summary>
        internal static string config_hdr1 {
            get {
                return ResourceManager.GetString("config_hdr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you receive an ECS message, the address of the content server (public or private) will be specified in the message header and the configuration you have created for that server will be used to retrieve the message content..
        /// </summary>
        internal static string config_hdr2 {
            get {
                return ResourceManager.GetString("config_hdr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration of the default content server is used when you send an ECS message or when you reply to or forward one whose content is hosted on a different server..
        /// </summary>
        internal static string config_hdr3 {
            get {
                return ResourceManager.GetString("config_hdr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChiaraMail Content Server.
        /// </summary>
        internal static string config_public_server_description {
            get {
                return ResourceManager.GetString("config_public_server_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your organization has its own ECS server then you should also enter the server URL and port..
        /// </summary>
        internal static string config_server {
            get {
                return ResourceManager.GetString("config_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-Content-Pointer.
        /// </summary>
        internal static string content_header {
            get {
                return ResourceManager.GetString("content_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content updated.
        /// </summary>
        internal static string content_updated {
            get {
                return ResourceManager.GetString("content_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this box is checked the message content will be encrypted before sending it to the server..
        /// </summary>
        internal static string default_encrypt_caption {
            get {
                return ResourceManager.GetString("default_encrypt_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this box and the &apos;Send as ECS&apos; box are checked, messages will include the actual content, rather than placeholders..
        /// </summary>
        internal static string default_include_content_caption {
            get {
                return ResourceManager.GetString("default_include_content_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this box is checked, mail will be sent using ECS..
        /// </summary>
        internal static string default_on_caption {
            get {
                return ResourceManager.GetString("default_on_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 443.
        /// </summary>
        internal static string default_port {
            get {
                return ResourceManager.GetString("default_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.chiaramail.com.
        /// </summary>
        internal static string default_server {
            get {
                return ResourceManager.GetString("default_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_content {
            get {
                object obj = ResourceManager.GetObject("delete_content", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete32 {
            get {
                object obj = ResourceManager.GetObject("Delete32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow mail forwarding.
        /// </summary>
        internal static string description_allow_forwarding {
            get {
                return ResourceManager.GetString("description_allow_forwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Message Content.
        /// </summary>
        internal static string description_delete_content {
            get {
                return ResourceManager.GetString("description_delete_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mail using ECS.
        /// </summary>
        internal static string description_dynamic_content {
            get {
                return ResourceManager.GetString("description_dynamic_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ECS-enabled content.
        /// </summary>
        internal static string description_edit_content {
            get {
                return ResourceManager.GetString("description_edit_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt ECS-enabled content.
        /// </summary>
        internal static string description_encrypted {
            get {
                return ResourceManager.GetString("description_encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get help for using ChiaraMail for Outlook.
        /// </summary>
        internal static string description_help {
            get {
                return ResourceManager.GetString("description_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include original content.
        /// </summary>
        internal static string description_no_placeholder {
            get {
                return ResourceManager.GetString("description_no_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an email request to ChiaraMail support.
        /// </summary>
        internal static string description_support {
            get {
                return ResourceManager.GetString("description_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DummyUser {
            get {
                object obj = ResourceManager.GetObject("DummyUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-Content-Duration.
        /// </summary>
        internal static string duration_header {
            get {
                return ResourceManager.GetString("duration_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECS.
        /// </summary>
        internal static string ecs {
            get {
                return ResourceManager.GetString("ecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_content {
            get {
                object obj = ResourceManager.GetObject("edit_content", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message has embedded (inline) images
        ///so the content can&apos;t be separated from the envelope.
        ///Select OK to send the existing content with the envelope
        ///or Cancel to edit the message and remove the images..
        /// </summary>
        internal static string Embedded_Image_Prompt {
            get {
                return ResourceManager.GetString("Embedded_Image_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-Content-Key.
        /// </summary>
        internal static string encrypt_key_header {
            get {
                return ResourceManager.GetString("encrypt_key_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-Content-Key2.
        /// </summary>
        internal static string encrypt_key_header2 {
            get {
                return ResourceManager.GetString("encrypt_key_header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Envelope2013 {
            get {
                object obj = ResourceManager.GetObject("Envelope2013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an ECS ephemeral message which can only be displayed on Android devices..
        /// </summary>
        internal static string ephemeral_content {
            get {
                return ResourceManager.GetString("ephemeral_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify ECS sender {0}: {1}.
        /// </summary>
        internal static string error_checking_registration {
            get {
                return ResourceManager.GetString("error_checking_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem updating the message content: {0}{1}.
        /// </summary>
        internal static string error_deleting_content {
            get {
                return ResourceManager.GetString("error_deleting_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching content: {0}{1}.
        /// </summary>
        internal static string error_fetching_content {
            get {
                return ResourceManager.GetString("error_fetching_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error storing content: {0){1}.
        /// </summary>
        internal static string error_storing_content {
            get {
                return ResourceManager.GetString("error_storing_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating content: {0}{1}.
        /// </summary>
        internal static string error_updating_content {
            get {
                return ResourceManager.GetString("error_updating_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot; onLoad=&quot;RibbonLoad&quot;&gt;
        ///  &lt;backstage&gt;
        ///    &lt;tab idMso=&quot;TabAccounts&quot;&gt;
        ///      &lt;firstColumn&gt;
        ///        &lt;group id=&quot;groupChiaraAccount&quot; insertAfterMso=&quot;GroupAccountInformation&quot;
        ///                getLabel=&quot;GetLabel&quot; getHelperText=&quot;GetDescription&quot; style=&quot;normal&quot;&gt;
        ///          &lt;primaryItem&gt;
        ///            &lt;menu id=&quot;buttonChiaraMailMenu&quot; getLabel=&quot;GetLabel&quot; getScreentip=&quot;GetScreentip&quot;
        ///                    getImage= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExplorerRibbon {
            get {
                return ResourceManager.GetString("ExplorerRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot; onLoad=&quot;RibbonLoad&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;contextualTabs&gt;
        ///      &lt;tabSet idMso=&quot;TabComposeTools&quot;&gt;
        ///        &lt;tab idMso=&quot;TabMessage&quot;&gt;
        ///          &lt;group id=&quot;groupChiaraMail&quot;  getLabel=&quot;GetLabel&quot;&gt;
        ///            &lt;toggleButton id=&quot;toggleDynamicEx&quot; getLabel=&quot;GetLabel&quot; size=&quot;normal&quot;
        ///               onAction=&quot;OnPress&quot; getPressed=&quot;GetPressed&quot; getImage=&quot;GetImage&quot;
        ///                getScreentip=&quot;GetScreentip&quot; getDe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExplorerRibbon2013 {
            get {
                return ResourceManager.GetString("ExplorerRibbon2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem retrieving content from the ECS server for &apos;{0}&apos;:{1}{2}.
        /// </summary>
        internal static string fetch_content_error {
            get {
                return ResourceManager.GetString("fetch_content_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name:.
        /// </summary>
        internal static string file_name_label {
            get {
                return ResourceManager.GetString("file_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t configured {0} e-mail address{1}to send or receive ECS-enabled content!{1}{1}Do you still want to close this form?.
        /// </summary>
        internal static string final_validation_prompt {
            get {
                return ResourceManager.GetString("final_validation_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string form_version {
            get {
                return ResourceManager.GetString("form_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Forward {
            get {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string from_label {
            get {
                return ResourceManager.GetString("from_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;customUI onLoad=&quot;RibbonLoad&quot; xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot;&gt;
        ///    &lt;ribbon&gt;
        ///        &lt;tabs&gt;
        ///            &lt;tab idMso=&quot;TabNewMailMessage&quot;&gt;
        ///                &lt;group id=&quot;groupChiaraMail&quot; getLabel=&quot;GetLabel&quot;&gt;
        ///                    &lt;toggleButton id=&quot;toggleDynamic&quot; getLabel=&quot;GetLabel&quot; size=&quot;normal&quot;
        ///                       onAction=&quot;OnPress&quot; getPressed=&quot;GetPressed&quot; getImage=&quot;GetImage&quot;
        ///                        getScreentip=&quot;GetScreentip&quot; getDescript [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InspectorRibbonCompose {
            get {
                return ResourceManager.GetString("InspectorRibbonCompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI onLoad=&quot;RibbonLoad&quot; xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab idMso=&quot;TabNewMailMessage&quot;&gt;
        ///        &lt;group id=&quot;groupChiaraMail&quot;  getLabel=&quot;GetLabel&quot;&gt;
        ///          &lt;toggleButton id=&quot;toggleDynamic&quot; getLabel=&quot;GetLabel&quot; size=&quot;normal&quot;
        ///             onAction=&quot;OnPress&quot; getPressed=&quot;GetPressed&quot; getImage=&quot;GetImage&quot;
        ///              getScreentip=&quot;GetScreentip&quot; getDescription=&quot;GetDescription&quot;
        ///              getEnabled=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InspectorRibbonCompose2010 {
            get {
                return ResourceManager.GetString("InspectorRibbonCompose2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;customUI onLoad=&quot;RibbonLoad&quot; xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab idMso=&quot;TabReadMessage&quot;&gt;
        ///        &lt;group id=&quot;groupChiaraMailRead&quot; getLabel=&quot;GetLabel&quot;&gt;
        ///          &lt;button id=&quot;buttonEditContent&quot; getLabel=&quot;GetLabel&quot; size=&quot;large&quot;
        ///             onAction=&quot;OnClick&quot; getImage=&quot;GetImage&quot; getEnabled=&quot;GetEnabled&quot;
        ///              getScreentip=&quot;GetScreentip&quot; getDescription=&quot;GetDescription&quot;/&gt;
        ///          &lt;button id=&quot;button [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InspectorRibbonRead {
            get {
                return ResourceManager.GetString("InspectorRibbonRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI onLoad=&quot;RibbonLoad&quot; xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab idMso=&quot;TabReadMessage&quot;&gt;
        ///        &lt;group id=&quot;groupChiaraMailRead&quot; getLabel=&quot;GetLabel&quot;&gt;
        ///          &lt;button id=&quot;buttonEditContent&quot; getLabel=&quot;GetLabel&quot; size=&quot;large&quot;
        ///             onAction=&quot;OnClick&quot; getImage=&quot;GetImage&quot; getEnabled=&quot;GetEnabled&quot;
        ///              getScreentip=&quot;GetScreentip&quot; getDescription=&quot;GetDescription&quot;/&gt;
        ///          &lt;button id=&quot;butto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InspectorRibbonRead2010 {
            get {
                return ResourceManager.GetString("InspectorRibbonRead2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ECS password is not valid.
        /// </summary>
        internal static string invalid_password {
            get {
                return ResourceManager.GetString("invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlicensed content server name/port.
        /// </summary>
        internal static string invalid_server {
            get {
                return ResourceManager.GetString("invalid_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECS Invitation.
        /// </summary>
        internal static string invite_alert_caption {
            get {
                return ResourceManager.GetString("invite_alert_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone that you selected with a valid address has already registered for ECS.
        /// </summary>
        internal static string invite_all_registered {
            get {
                return ResourceManager.GetString("invite_all_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to invite your contacts to register for ECS, so they are able to read your ECS-enabled messages?.
        /// </summary>
        internal static string invite_prompt {
            get {
                return ResourceManager.GetString("invite_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These names have been removed from the invitation{0}because they already have ECS accounts:{0}{1}.
        /// </summary>
        internal static string invite_registered_alert {
            get {
                return ResourceManager.GetString("invite_registered_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write to me with ECSMail, the next-generation e-mail program!.
        /// </summary>
        internal static string invite_subject {
            get {
                return ResourceManager.GetString("invite_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,{0}{0}I don&apos;t want Google to read my e-mail anymore, so I installed ECS support into my mail programs and I invite you to do the same. Besides protecting our privacy, the ECS products from ChiaraMail help protect us from email spoofing, in which others try to trick us into revealing our bank login credentials and such, and also enable us to change our e-mail after we&apos;ve sent it (Yes! Really!). As if that weren&apos;t enough, ECS technology allows us to send attachments of practically unlimited size and also s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string invite_text {
            get {
                return ResourceManager.GetString("invite_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem uploading the message to the ECS server:.
        /// </summary>
        internal static string ItemSend_Upload_Problem {
            get {
                return ResourceManager.GetString("ItemSend_Upload_Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChiaraMail for Outlook Account Settings.
        /// </summary>
        internal static string label_account_settings {
            get {
                return ResourceManager.GetString("label_account_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow forwarding.
        /// </summary>
        internal static string label_allow_forwarding {
            get {
                return ResourceManager.GetString("label_allow_forwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChiaraMail for Outlook Settings.
        /// </summary>
        internal static string label_config_button {
            get {
                return ResourceManager.GetString("label_config_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChiaraMail for Outlook Settings.
        /// </summary>
        internal static string label_config_group {
            get {
                return ResourceManager.GetString("label_config_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Content.
        /// </summary>
        internal static string label_delete_content {
            get {
                return ResourceManager.GetString("label_delete_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as ECS.
        /// </summary>
        internal static string label_dynamic_content {
            get {
                return ResourceManager.GetString("label_dynamic_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Content.
        /// </summary>
        internal static string label_edit_content {
            get {
                return ResourceManager.GetString("label_edit_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt content.
        /// </summary>
        internal static string label_encrypted {
            get {
                return ResourceManager.GetString("label_encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending options.
        /// </summary>
        internal static string label_group_name {
            get {
                return ResourceManager.GetString("label_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChiaraMail for Outlook Help.
        /// </summary>
        internal static string label_help {
            get {
                return ResourceManager.GetString("label_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string label_help_backstage {
            get {
                return ResourceManager.GetString("label_help_backstage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChiaraMail for Outlook.
        /// </summary>
        internal static string label_help_group {
            get {
                return ResourceManager.GetString("label_help_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ECS Invitation.
        /// </summary>
        internal static string label_invite {
            get {
                return ResourceManager.GetString("label_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include content.
        /// </summary>
        internal static string label_no_placeholder {
            get {
                return ResourceManager.GetString("label_no_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Support from ChiaraMail.
        /// </summary>
        internal static string label_support {
            get {
                return ResourceManager.GetString("label_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPM.Note.ChiaraMail.
        /// </summary>
        internal static string message_class_CM {
            get {
                return ResourceManager.GetString("message_class_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;META HTTP-EQUIV=&quot;Content-Type&quot; CONTENT=&quot;text/html; charset=us-ascii&quot;&gt;.
        /// </summary>
        internal static string meta {
            get {
                return ResourceManager.GetString("meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply the password..
        /// </summary>
        internal static string Missing_Password {
            get {
                return ResourceManager.GetString("Missing_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ECS Password.
        /// </summary>
        internal static string missing_password_setting {
            get {
                return ResourceManager.GetString("missing_password_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply the ECS server port number..
        /// </summary>
        internal static string Missing_Port {
            get {
                return ResourceManager.GetString("Missing_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply the ECS server name..
        /// </summary>
        internal static string Missing_Server_Name {
            get {
                return ResourceManager.GetString("Missing_Server_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ECS setting(s): {0}{1}.
        /// </summary>
        internal static string missing_settings {
            get {
                return ResourceManager.GetString("missing_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open for Editing.
        /// </summary>
        internal static string open_for_editing {
            get {
                return ResourceManager.GetString("open_for_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open_menu_option {
            get {
                return ResourceManager.GetString("open_menu_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your protection and privacy, this message was sent using ECS® technology, but your mail client is not yet enabled for ECS. To read this secure message, please download the appropriate ECS extension for your mail client or one of our ECS-enabled mobile mail clients (http://www.chiaramailcorp.com/downloads/)..
        /// </summary>
        internal static string placeholder_html {
            get {
                return ResourceManager.GetString("placeholder_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mail client is not enabled/configured for Envelope-Content Splitting (ECS) technology. In order to send or view ECS messages, your mail client must be enabled and configured for ECS. Mozilla Thunderbird and Microsoft Outlook users must install the free ECS extension
        ///(&lt;a href=&quot;http://www.chiaramail.com/download_extension.html&quot;&gt;http://www.chiaramail.com/download_extension.html&lt;/a&gt;) and Thunderbird users must register for content service, also free (&lt;a href=&quot;http://www.chiaramail.com/index.jsp&quot;&gt;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string placeholder_html2 {
            get {
                return ResourceManager.GetString("placeholder_html2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message was sent using &lt;a href=&apos;http://www.chiaramail.com/technology.html&apos;&gt;ECS technology&lt;/a&gt;, but your mail client does not support ECS. Please download and install the appropriate ECS-enabling software for your mail client (&lt;a href=&apos;http://www.chiaramail.com/download_ecs.html&apos;&gt;http://www.chiaramail.com/download_ecs.html&lt;/a&gt;) to read this message..
        /// </summary>
        internal static string placeholder_html3 {
            get {
                return ResourceManager.GetString("placeholder_html3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your protection and privacy, this message was sent using ECS technology, but your mail client is not yet enabled for ECS. To read this secure message, please download (https://web.chiaramail.com/downloads) the appropriate ECS extension for your mail client or one of our ECS-enabled mobile mail clients..
        /// </summary>
        internal static string placeholder_text {
            get {
                return ResourceManager.GetString("placeholder_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mail client requires the dynamic content extension in order to view dynamic content mail. Select the following link to download and install the extension: http://www.chiaramail.com/download_extension.html..
        /// </summary>
        internal static string placeholder_text0 {
            get {
                return ResourceManager.GetString("placeholder_text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message was sent using HYPERLINK &quot;http://www.chiaramail.com/technology.html&quot;ECS technology, but your mail client does not support ECS. Please download and install the appropriate ECS-enabling software for your mail client (http://www.chiaramail.com/download_extension.html) to read this message..
        /// </summary>
        internal static string placeholder_text1 {
            get {
                return ResourceManager.GetString("placeholder_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mail client is not enabled/configured for Envelope-Content Splitting (ECS) technology. In order to send or view ECS messages, your mail client must be enabled and configured for ECS. Mozilla Thunderbird and Microsoft Outlook users must install the free ECS extension
        ///(http://www.chiaramail.com/download_extension.html) and Thunderbird users must register for content service, also free (http://www.chiaramail.com/index.jsp). ECSMail for Android users need only install the app and configure their mail acco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string placeholder_text2 {
            get {
                return ResourceManager.GetString("placeholder_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message was sent using ECS technology (http://www.chiaramail.com/technology.html), but your mail client does not support ECS. Please download and install the appropriate ECS-enabling software for your mail client (http://www.chiaramail.com/download_ecs.html) to read this message..
        /// </summary>
        internal static string placeholder_text3 {
            get {
                return ResourceManager.GetString("placeholder_text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-Content-Server-Port.
        /// </summary>
        internal static string port_header {
            get {
                return ResourceManager.GetString("port_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number out of range [1-1023]..
        /// </summary>
        internal static string port_out_of_range {
            get {
                return ResourceManager.GetString("port_out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChiaraMail for Outlook.
        /// </summary>
        internal static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mail account already has a configuration for &apos;{0}&apos;!{1}{1}Please enter a different content server name or select another port..
        /// </summary>
        internal static string prompt_config_duplicate_host {
            get {
                return ResourceManager.GetString("prompt_config_duplicate_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mail account already has a configuration named &apos;{0}&apos;!.
        /// </summary>
        internal static string prompt_config_duplicate_name {
            get {
                return ResourceManager.GetString("prompt_config_duplicate_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not appear to be a valid server name!.
        /// </summary>
        internal static string prompt_config_invalid_server_name {
            get {
                return ResourceManager.GetString("prompt_config_invalid_server_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a name for this configuration!.
        /// </summary>
        internal static string prompt_config_missing_name {
            get {
                return ResourceManager.GetString("prompt_config_missing_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply the name of the content server!.
        /// </summary>
        internal static string prompt_config_missing_server {
            get {
                return ResourceManager.GetString("prompt_config_missing_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the content in this message?.
        /// </summary>
        internal static string prompt_delete_content_confirm {
            get {
                return ResourceManager.GetString("prompt_delete_content_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes for the &apos;{0}&apos; account?.
        /// </summary>
        internal static string prompt_save_config_changes {
            get {
                return ResourceManager.GetString("prompt_save_config_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/mapi/string/{00020386-0000-0000-C000-000000000046}/.
        /// </summary>
        internal static string public_strings_root {
            get {
                return ResourceManager.GetString("public_strings_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ReadECS {
            get {
                object obj = ResourceManager.GetObject("ReadECS", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error, unable to get content server password.
        /// </summary>
        internal static string register_user_failed {
            get {
                return ResourceManager.GetString("register_user_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reply {
            get {
                object obj = ResourceManager.GetObject("Reply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReplyAll {
            get {
                object obj = ResourceManager.GetObject("ReplyAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveAs {
            get {
                object obj = ResourceManager.GetObject("SaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send this email with ECS-enabled content.
        /// </summary>
        internal static string screentip_dynamic_content {
            get {
                return ResourceManager.GetString("screentip_dynamic_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the content of this email.
        /// </summary>
        internal static string screentip_edit_content {
            get {
                return ResourceManager.GetString("screentip_edit_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt the ECS-enabled content.
        /// </summary>
        internal static string screentip_encrypted {
            get {
                return ResourceManager.GetString("screentip_encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite your contacts to use ECS.
        /// </summary>
        internal static string screentip_invite {
            get {
                return ResourceManager.GetString("screentip_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender &apos;{0}&apos; is not registered for ECS.
        /// </summary>
        internal static string sender_not_registered {
            get {
                return ResourceManager.GetString("sender_not_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent:.
        /// </summary>
        internal static string sent_label {
            get {
                return ResourceManager.GetString("sent_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-Content-Server-Name.
        /// </summary>
        internal static string server_header {
            get {
                return ResourceManager.GetString("server_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string size_label {
            get {
                return ResourceManager.GetString("size_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snake_loader_cornflower {
            get {
                object obj = ResourceManager.GetObject("snake_loader_cornflower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender does not appear to be legitimate.
        /// </summary>
        internal static string spoofed_sender_address {
            get {
                return ResourceManager.GetString("spoofed_sender_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        internal static string subject_label {
            get {
                return ResourceManager.GetString("subject_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string to_label {
            get {
                return ResourceManager.GetString("to_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure account settings for ChiaraMail for Outlook.
        /// </summary>
        internal static string tooltip_config_button {
            get {
                return ResourceManager.GetString("tooltip_config_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown content server name/port.
        /// </summary>
        internal static string unknown_server {
            get {
                return ResourceManager.GetString("unknown_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon UnreadECS {
            get {
                object obj = ResourceManager.GetObject("UnreadECS", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-Update-Pointer.
        /// </summary>
        internal static string update_header_pointer {
            get {
                return ResourceManager.GetString("update_header_pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-Update-Port.
        /// </summary>
        internal static string update_header_port {
            get {
                return ResourceManager.GetString("update_header_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-Update-Sender.
        /// </summary>
        internal static string update_header_sender {
            get {
                return ResourceManager.GetString("update_header_sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-Update-Server.
        /// </summary>
        internal static string update_header_server {
            get {
                return ResourceManager.GetString("update_header_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-User-Agent.
        /// </summary>
        internal static string user_agent_header {
            get {
                return ResourceManager.GetString("user_agent_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ChiaraMail-Allow-Forwarding.
        /// </summary>
        internal static string user_allow_forwarding_header {
            get {
                return ResourceManager.GetString("user_allow_forwarding_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking to see who is already registered for ECS....
        /// </summary>
        internal static string wait_check_registered {
            get {
                return ResourceManager.GetString("wait_check_registered", resourceCulture);
            }
        }
    }
}
